
version: '3'
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A nova_loop.celery_app worker -l info
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A nova_loop.celery_app beat -l info
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
